apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    # CRITICAL: Allows uploads up to 16MB for the MP3 POST requests
    nginx.ingress.kubernetes.io/proxy-body-size: 16m 
spec:
  rules:
  - http:
      paths:
      # Route all traffic to the rest-service
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rest-service
            port:
              number: 5000

